[2022-11-18T21:12:56.002+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: LocalIngestionDag.ingest manual__2022-11-18T21:12:51.160814+00:00 [queued]>
[2022-11-18T21:12:56.016+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: LocalIngestionDag.ingest manual__2022-11-18T21:12:51.160814+00:00 [queued]>
[2022-11-18T21:12:56.017+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-18T21:12:56.017+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-11-18T21:12:56.017+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-18T21:12:56.041+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): ingest> on 2022-11-18 21:12:51.160814+00:00
[2022-11-18T21:12:56.051+0000] {standard_task_runner.py:55} INFO - Started process 1048 to run task
[2022-11-18T21:12:56.059+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'LocalIngestionDag', 'ingest', 'manual__2022-11-18T21:12:51.160814+00:00', '--job-id', '85', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_local.py', '--cfg-path', '/tmp/tmp0n0s51u7']
[2022-11-18T21:12:56.063+0000] {standard_task_runner.py:83} INFO - Job 85: Subtask ingest
[2022-11-18T21:12:56.163+0000] {task_command.py:376} INFO - Running <TaskInstance: LocalIngestionDag.ingest manual__2022-11-18T21:12:51.160814+00:00 [running]> on host b8836091f311
[2022-11-18T21:12:56.219+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:204: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-11-18T21:12:56.275+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=LocalIngestionDag
AIRFLOW_CTX_TASK_ID=ingest
AIRFLOW_CTX_EXECUTION_DATE=2022-11-18T21:12:51.160814+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-18T21:12:51.160814+00:00
[2022-11-18T21:12:56.276+0000] {logging_mixin.py:137} INFO - yellow_taxi_2022-11 /opt/***/output_2022-11.csv.gz 2022-11-18T21:12:51.160814+00:00
[2022-11-18T21:12:56.287+0000] {logging_mixin.py:137} INFO - connection established successfully, inserting data...
[2022-11-18T21:12:56.289+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ingest_script.py", line 18, in ingest_callable
    df_iter = pd.read_csv(csv_file, iterator=True, chunksize=100000)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 645, in get_handle
    **compression_args,
  File "/usr/local/lib/python3.7/gzip.py", line 168, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/output_2022-11.csv.gz'
[2022-11-18T21:12:56.303+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=LocalIngestionDag, task_id=ingest, execution_date=20221118T211251, start_date=20221118T211256, end_date=20221118T211256
[2022-11-18T21:12:56.319+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 85 for task ingest ([Errno 2] No such file or directory: '/opt/airflow/output_2022-11.csv.gz'; 1048)
[2022-11-18T21:12:56.351+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-11-18T21:12:56.379+0000] {taskinstance.py:2623} INFO - 0 downstream tasks scheduled from follow-on schedule check
